import { useEffect, useRef, useState } from "react";
import { useRoute, useLocation } from "wouter";
import AppLayout from "@/components/app-layout";
import { Button } from "@/components/ui/button";
import { Download, FileText, Share2, Loader2, ArrowLeft, RefreshCw, Briefcase, Presentation, Code, Globe, Users, ExternalLink, Hash, MessageCircle, Clock, AlertTriangle, CheckCircle, Rabbit, ChevronDown, ChevronUp, Target } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown from "react-markdown";
import type { Project, Conversation } from "@shared/schema";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

type CommunityData = {
  reddit?: Array<{ name: string; subscribers: string; relevance: string }>;
  discord?: Array<{ name: string; description: string; invite_hint: string }>;
  twitter?: Array<{ hashtag: string; usage: string; tip: string }>;
  other?: Array<{ platform: string; community: string; description: string }>;
  timing_tips?: string[];
};

type RealityCheckData = {
  time_to_mvp?: { estimate: string; hours_per_week: string; total_hours: string; reality: string };
  skills_required?: Array<{ skill: string; level: string; learning_time: string }>;
  complexity_score?: { score: number; label: string; breakdown: string };
  hidden_work?: string[];
  financial_reality?: { minimum_budget: string; what_it_covers: string; hidden_costs: string[] };
  opportunity_cost?: { what_else_could_you_do: string; is_now_the_right_time: boolean; reasoning: string };
  red_flags?: string[];
  green_flags?: string[];
  bottom_line?: string;
};

type ProjectWithConversation = Project & { conversation?: Conversation };
type PRDFormat = "full" | "business" | "pitch";

const FORMAT_OPTIONS = [
  { id: "full" as PRDFormat, label: "Dev-Ready PRD", icon: Code, description: "Technical specs for developers" },
  { id: "business" as PRDFormat, label: "Business Plan", icon: Briefcase, description: "For investors & stakeholders" },
  { id: "pitch" as PRDFormat, label: "Pitch Summary", icon: Presentation, description: "One-page pitch deck" },
];

const fadeIn = {
  hidden: { opacity: 0, y: 10 },
  visible: { opacity: 1, y: 0 }
};

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 }
  }
};

export default function PrdView() {
  const [matchApp, paramsApp] = useRoute("/app/prd/:id");
  const [matchLegacy, paramsLegacy] = useRoute("/prd/:id");
  const params = paramsApp || paramsLegacy;
  const [, setLocation] = useLocation();
  const [project, setProject] = useState<ProjectWithConversation | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentFormat, setCurrentFormat] = useState<PRDFormat>("full");
  const [isGeneratingLandingPage, setIsGeneratingLandingPage] = useState(false);
  const [isFindingCommunities, setIsFindingCommunities] = useState(false);
  const [communities, setCommunities] = useState<CommunityData | null>(null);
  const [isCheckingReality, setIsCheckingReality] = useState(false);
  const [realityCheck, setRealityCheck] = useState<RealityCheckData | null>(null);
  const [viewMode, setViewMode] = useState<"formatted" | "raw">("formatted");
  const [isPrdExpanded, setIsPrdExpanded] = useState(false);
  const hasAutoGeneratedRef = useRef(false);
  const { toast } = useToast();

  const projectId = params?.id ? parseInt(params.id) : null;

  useEffect(() => {
    if (projectId) {
      loadProject();
    }
  }, [projectId]);

  const loadProject = async () => {
    if (!projectId) return;
    
    try {
      const response = await fetch(`/api/projects/${projectId}`);
      if (!response.ok) throw new Error("Failed to load project");
      
      const data = await response.json();
      setProject(data);
      
      // If no PRD content yet, generate it once (guard against duplicate
      // calls, e.g. React StrictMode double-mount in development)
      if (!data.prdContent && !hasAutoGeneratedRef.current) {
        hasAutoGeneratedRef.current = true;
        await generatePRD();
      }
    } catch (error) {
      console.error("Error loading project:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to load project",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const generatePRD = async (format: PRDFormat = "full") => {
    if (!projectId) return;
    
    setIsGenerating(true);
    setCurrentFormat(format);
    try {
      const response = await fetch(`/api/projects/${projectId}/generate-prd`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ format }),
      });
      
      if (!response.ok) throw new Error("Failed to generate PRD");
      
      const data = await response.json();
      setProject(prev => prev ? { ...prev, prdContent: data.prdContent } : null);
      
      const formatLabel = FORMAT_OPTIONS.find(f => f.id === format)?.label || "PRD";
      toast({
        title: `${formatLabel} Generated`,
        description: "Your document has been created successfully!",
      });
    } catch (error) {
      console.error("Error generating PRD:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to generate PRD",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadMarkdown = () => {
    if (!project?.prdContent) return;
    
    const blob = new Blob([project.prdContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.title.replace(/[^a-z0-9]/gi, "_")}_PRD.md`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast({
      title: "Downloaded",
      description: "PRD exported as Markdown",
    });
  };

  const downloadJSON = () => {
    if (!project) return;
    
    const exportData = {
      title: project.title,
      description: project.description,
      type: project.type,
      rawIdea: project.rawIdea,
      prdContent: project.prdContent,
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
    };
    
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.title.replace(/[^a-z0-9]/gi, "_")}_PRD.json`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast({
      title: "Downloaded",
      description: "PRD exported as JSON",
    });
  };

  const copyToClipboard = async () => {
    if (!project?.prdContent) return;
    
    try {
      await navigator.clipboard.writeText(project.prdContent);
      toast({
        title: "Copied",
        description: "PRD copied to clipboard",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to copy to clipboard",
      });
    }
  };

  const generateLandingPage = async () => {
    if (!projectId) return;
    
    setIsGeneratingLandingPage(true);
    try {
      const response = await fetch(`/api/projects/${projectId}/generate-landing-page`, {
        method: "POST",
      });
      
      if (!response.ok) throw new Error("Failed to generate landing page");
      
      const data = await response.json();
      
      // Download the HTML file
      const blob = new Blob([data.html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${project?.title.replace(/[^a-z0-9]/gi, "_")}_landing_page.html`;
      a.click();
      URL.revokeObjectURL(url);
      
      toast({
        title: "Landing Page Generated",
        description: "Download started! Open the HTML file to preview.",
      });
    } catch (error) {
      console.error("Error generating landing page:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to generate landing page",
      });
    } finally {
      setIsGeneratingLandingPage(false);
    }
  };

  const findCommunities = async () => {
    if (!projectId) return;
    
    setIsFindingCommunities(true);
    try {
      const response = await fetch(`/api/projects/${projectId}/find-communities`, {
        method: "POST",
      });
      
      if (!response.ok) throw new Error("Failed to find communities");
      
      const data = await response.json();
      setCommunities(data);
      
      toast({
        title: "Communities Found",
        description: "Scroll down to see where to share your idea!",
      });
    } catch (error) {
      console.error("Error finding communities:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to find communities",
      });
    } finally {
      setIsFindingCommunities(false);
    }
  };

  const checkReality = async () => {
    if (!projectId) return;
    
    setIsCheckingReality(true);
    try {
      const response = await fetch(`/api/projects/${projectId}/reality-check`, {
        method: "POST",
      });
      
      if (!response.ok) throw new Error("Failed to run reality check");
      
      const data = await response.json();
      setRealityCheck(data);
      
      toast({
        title: "Reality Check Complete",
        description: "Scroll down to see the honest assessment.",
      });
    } catch (error) {
      console.error("Error running reality check:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to run reality check",
      });
    } finally {
      setIsCheckingReality(false);
    }
  };

  if (isLoading) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center h-full min-h-[50vh]">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      </AppLayout>
    );
  }

  if (!project) {
    return (
      <AppLayout>
        <div className="flex flex-col items-center justify-center h-full min-h-[50vh]">
          <p className="text-muted-foreground mb-4">Project not found</p>
          <Button onClick={() => setLocation("/app")}>Go to Dashboard</Button>
        </div>
      </AppLayout>
    );
  }

  if (isGenerating) {
    return (
      <AppLayout>
        <div className="flex flex-col items-center justify-center h-full min-h-[50vh] gap-6">
          <div className="relative">
            <div className="absolute inset-0 bg-primary/20 blur-xl rounded-full" />
            <Loader2 className="w-16 h-16 animate-spin text-primary relative z-10" />
          </div>
          <div className="text-center max-w-md px-4">
            <h2 className="text-3xl font-display font-bold mb-3 tracking-tight">Forging Document...</h2>
            <p className="text-muted-foreground text-lg">AI is crafting a comprehensive specification from your conversation.</p>
          </div>
        </div>
      </AppLayout>
    );
  }

  if (!project.prdContent) {
    return (
      <AppLayout>
        <div className="flex flex-col items-center justify-center h-full min-h-[50vh] gap-6">
          <div className="w-20 h-20 bg-muted rounded-2xl flex items-center justify-center">
            <FileText className="w-10 h-10 text-muted-foreground/50" />
          </div>
          <div className="text-center">
            <h2 className="text-2xl font-display font-bold mb-3">No Document Yet</h2>
            <p className="text-muted-foreground mb-6">Complete your interview to generate specs.</p>
            <Button size="lg" className="rounded-xl" onClick={() => setLocation("/app")}>Back to Foundry</Button>
          </div>
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <div className="container mx-auto px-4 py-8 md:px-8 max-w-5xl">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-10 pb-6 border-b border-border/50 gap-6">
          <div className="flex items-start gap-4">
            <Button 
              variant="ghost" 
              size="icon"
              className="mt-1 shrink-0 text-muted-foreground hover:text-foreground"
              onClick={() => setLocation(`/app/ideas/${project.id}`)}
              data-testid="button-back"
            >
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-3xl md:text-4xl font-display font-bold tracking-tight mb-2 text-foreground">{project.title}</h1>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-0.5 rounded-md bg-secondary text-secondary-foreground text-xs font-semibold">{project.type}</span>
                <span className="text-sm text-muted-foreground">Generated Document</span>
              </div>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 md:ml-auto">
            <Button 
              variant="outline" 
              className="gap-2 font-semibold"
              onClick={copyToClipboard}
              data-testid="button-copy"
            >
              <Share2 className="w-4 h-4 text-muted-foreground" />
              Copy
            </Button>
            
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="gap-2 font-semibold" data-testid="button-export">
                  <Download className="w-4 h-4" />
                  Export
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-48">
                <DropdownMenuItem onClick={downloadMarkdown} data-testid="export-markdown" className="cursor-pointer gap-2 py-2">
                  <FileText className="w-4 h-4 text-primary" />
                  Download Markdown
                </DropdownMenuItem>
                <DropdownMenuItem onClick={downloadJSON} data-testid="export-json" className="cursor-pointer gap-2 py-2">
                  <Code className="w-4 h-4 text-blue-500" />
                  Download JSON
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>

            {project.conversation && (
              <Button 
                onClick={() => project.conversation && setLocation(`/app/conversation/${project.conversation.id}`)}
                data-testid="button-continue-chat"
                className="gap-2 font-semibold bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700 text-white border-0 shadow-md"
              >
                <MessageCircle className="w-4 h-4" />
                Refine in Chat
              </Button>
            )}
          </div>
        </div>

        {/* Validation Tools Section - Now First */}
        <motion.div initial="hidden" animate="visible" variants={staggerContainer} className="mb-12">
          <motion.div variants={fadeIn} className="mb-8">
            <h2 className="text-2xl font-display font-bold mb-2 flex items-center gap-2">
              <Target className="w-6 h-6 text-primary" />
              Market Validation
            </h2>
            <p className="text-muted-foreground text-lg">Test your concept in the real world before writing code.</p>
          </motion.div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-8">
            <motion.div variants={fadeIn} className="p-6 rounded-2xl border bg-card shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-bl-full -mr-10 -mt-10 transition-transform group-hover:scale-110" />
              <div className="relative z-10">
                <div className="flex items-center gap-4 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center border border-primary/20 shadow-inner">
                    <Globe className="w-6 h-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg">Landing Page</h3>
                    <p className="text-sm font-medium text-muted-foreground">HTML coming soon page</p>
                  </div>
                </div>
                <Button 
                  onClick={generateLandingPage}
                  disabled={isGeneratingLandingPage}
                  className="w-full h-12 rounded-xl font-semibold gap-2 shadow-sm"
                  data-testid="button-generate-landing-page"
                >
                  {isGeneratingLandingPage ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Forging Page...
                    </>
                  ) : (
                    <>
                      <Download className="w-5 h-5" />
                      Generate & Download
                    </>
                  )}
                </Button>
              </div>
            </motion.div>

            <motion.div variants={fadeIn} className="p-6 rounded-2xl border bg-card shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-cyan-500/5 rounded-bl-full -mr-10 -mt-10 transition-transform group-hover:scale-110" />
              <div className="relative z-10">
                <div className="flex items-center gap-4 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-cyan-500/10 flex items-center justify-center border border-cyan-500/20 shadow-inner">
                    <Users className="w-6 h-6 text-cyan-500" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg">Community Finder</h3>
                    <p className="text-sm font-medium text-muted-foreground">Reddit, Discord & Twitter</p>
                  </div>
                </div>
                <Button 
                  onClick={findCommunities}
                  disabled={isFindingCommunities}
                  variant="outline"
                  className="w-full h-12 rounded-xl font-semibold gap-2 border-2 hover:bg-muted"
                  data-testid="button-find-communities"
                >
                  {isFindingCommunities ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Scouting...
                    </>
                  ) : (
                    <>
                      <Users className="w-5 h-5" />
                      Find Where Users Hang Out
                    </>
                  )}
                </Button>
              </div>
            </motion.div>

            <motion.div variants={fadeIn} className="p-6 rounded-2xl border bg-card shadow-sm hover:shadow-md transition-shadow md:col-span-2 relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/5 rounded-bl-full -mr-20 -mt-20 transition-transform group-hover:scale-110" />
              <div className="relative z-10">
                <div className="flex items-center gap-4 mb-3">
                  <div className="w-12 h-12 rounded-xl bg-amber-500/10 flex items-center justify-center border border-amber-500/20 shadow-inner">
                    <Rabbit className="w-6 h-6 text-amber-500" />
                  </div>
                  <div>
                    <h3 className="font-bold text-xl">Rabbit Hole Reality Check</h3>
                    <p className="text-sm font-medium text-amber-600 dark:text-amber-400">Brutally honest assessment of time and skill required</p>
                  </div>
                </div>
                <p className="text-muted-foreground mb-5 max-w-3xl leading-relaxed">
                  For founders who chase shiny objects. Get a realistic breakdown of whether this is worth your time right now based on the complexity of your specs.
                </p>
                <Button 
                  onClick={checkReality}
                  disabled={isCheckingReality}
                  variant="outline"
                  className="w-full md:w-auto h-12 px-8 rounded-xl font-semibold gap-2 border-2 border-amber-500/50 hover:bg-amber-500/10 text-amber-700 dark:text-amber-400 transition-colors"
                  data-testid="button-reality-check"
                >
                  {isCheckingReality ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Analyzing Complexity...
                    </>
                  ) : (
                    <>
                      <Clock className="w-5 h-5" />
                      Run Reality Check
                    </>
                  )}
                </Button>
              </div>
            </motion.div>
          </div>

          <AnimatePresence>
          {/* Reality Check Results */}
          {realityCheck && (
            <motion.div 
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              className="mb-12 p-6 md:p-8 rounded-3xl border-2 border-amber-500/30 bg-amber-500/5 overflow-hidden" 
              data-testid="reality-check-results"
            >
              <h3 className="text-2xl font-display font-bold mb-6 flex items-center gap-3">
                <Rabbit className="w-8 h-8 text-amber-500" />
                Reality Check Results
              </h3>

              {/* Bottom Line */}
              {realityCheck.bottom_line && (
                <div className="p-5 rounded-2xl bg-background border shadow-sm mb-8" data-testid="text-reality-bottom-line">
                  <p className="text-xl font-bold text-foreground leading-tight">{realityCheck.bottom_line}</p>
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Complexity Score */}
                {realityCheck.complexity_score && (
                  <div className="p-6 rounded-2xl bg-background border shadow-sm" data-testid="card-complexity-score">
                    <h4 className="font-bold text-lg mb-4 text-foreground/80 uppercase tracking-wider text-sm">Complexity Score</h4>
                    <div className="flex items-baseline gap-3 mb-3">
                      <div className="text-5xl font-display font-black text-amber-500" data-testid="text-complexity-score">{realityCheck.complexity_score.score}<span className="text-2xl text-muted-foreground">/10</span></div>
                      <div className="text-lg font-bold">{realityCheck.complexity_score.label}</div>
                    </div>
                    <p className="text-muted-foreground leading-relaxed">{realityCheck.complexity_score.breakdown}</p>
                  </div>
                )}

                {/* Time to MVP */}
                {realityCheck.time_to_mvp && (
                  <div className="p-6 rounded-2xl bg-background border shadow-sm" data-testid="card-time-commitment">
                    <h4 className="font-bold text-lg mb-4 text-foreground/80 uppercase tracking-wider text-sm flex items-center gap-2">
                      <Clock className="w-4 h-4 text-blue-500" />
                      Time Commitment
                    </h4>
                    <div className="space-y-3 mb-4">
                      <div className="flex justify-between items-center pb-2 border-b">
                        <span className="font-medium text-muted-foreground">Time to MVP</span>
                        <span className="font-bold text-foreground">{realityCheck.time_to_mvp.estimate}</span>
                      </div>
                      <div className="flex justify-between items-center pb-2 border-b">
                        <span className="font-medium text-muted-foreground">Hours / Week</span>
                        <span className="font-bold text-foreground">{realityCheck.time_to_mvp.hours_per_week}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="font-medium text-muted-foreground">Total Hours</span>
                        <span className="font-bold text-foreground">{realityCheck.time_to_mvp.total_hours}</span>
                      </div>
                    </div>
                    <div className="p-3 bg-muted/50 rounded-lg">
                      <p className="text-sm font-medium text-foreground/80">{realityCheck.time_to_mvp.reality}</p>
                    </div>
                  </div>
                )}

                {/* Financial Reality */}
                {realityCheck.financial_reality && (
                  <div className="p-6 rounded-2xl bg-background border shadow-sm" data-testid="card-financial-reality">
                    <h4 className="font-bold text-lg mb-4 text-foreground/80 uppercase tracking-wider text-sm">Financial Reality</h4>
                    <p className="text-4xl font-display font-black text-green-500 mb-2">{realityCheck.financial_reality.minimum_budget}</p>
                    <p className="font-medium text-foreground mb-4">{realityCheck.financial_reality.what_it_covers}</p>
                    {realityCheck.financial_reality.hidden_costs?.length > 0 && (
                      <div className="pt-4 border-t">
                        <span className="text-sm font-bold text-muted-foreground uppercase tracking-wider block mb-2">Hidden costs:</span>
                        <div className="flex flex-wrap gap-2">
                          {realityCheck.financial_reality.hidden_costs.map((cost, idx) => (
                            <span key={idx} className="px-2.5 py-1 bg-muted rounded-md text-xs font-medium">{cost}</span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* Opportunity Cost */}
                {realityCheck.opportunity_cost && (
                  <div className="p-6 rounded-2xl bg-background border shadow-sm">
                    <h4 className="font-bold text-lg mb-4 text-foreground/80 uppercase tracking-wider text-sm">Opportunity Cost</h4>
                    <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-bold mb-4 ${realityCheck.opportunity_cost.is_now_the_right_time ? "bg-green-500/10 text-green-600 border border-green-500/20" : "bg-red-500/10 text-red-600 border border-red-500/20"}`}>
                      {realityCheck.opportunity_cost.is_now_the_right_time ? <CheckCircle className="w-4 h-4" /> : <AlertTriangle className="w-4 h-4" />}
                      {realityCheck.opportunity_cost.is_now_the_right_time ? "Good timing" : "Consider waiting"}
                    </div>
                    <p className="font-bold text-foreground mb-2 leading-snug">{realityCheck.opportunity_cost.what_else_could_you_do}</p>
                    <p className="text-sm text-muted-foreground leading-relaxed">{realityCheck.opportunity_cost.reasoning}</p>
                  </div>
                )}
              </div>

              {/* Skills Required */}
              {realityCheck.skills_required && realityCheck.skills_required.length > 0 && (
                <div className="mt-8">
                  <h4 className="font-bold text-lg mb-4 text-foreground/80 uppercase tracking-wider text-sm">Skills Required</h4>
                  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                    {realityCheck.skills_required.map((skill, i) => (
                      <div key={i} className="p-4 rounded-xl bg-background border shadow-sm">
                        <div className="flex items-center justify-between mb-2">
                          <span className="font-bold">{skill.skill}</span>
                          <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${skill.level === "beginner" ? "bg-green-500/10 text-green-600 border-green-500/20" : skill.level === "intermediate" ? "bg-yellow-500/10 text-yellow-600 border-yellow-500/20" : "bg-red-500/10 text-red-600 border-red-500/20"}`}>
                            {skill.level}
                          </span>
                        </div>
                        <span className="text-sm text-muted-foreground font-medium">{skill.learning_time}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
                {/* Hidden Work */}
                {realityCheck.hidden_work && realityCheck.hidden_work.length > 0 && (
                  <div className="p-5 rounded-xl bg-background border">
                    <h4 className="font-bold mb-4 text-foreground/80 uppercase tracking-wider text-xs">Things People Forget</h4>
                    <ul className="space-y-3">
                      {realityCheck.hidden_work.map((item, i) => (
                        <li key={i} className="text-sm flex items-start gap-3 text-foreground/90">
                          <div className="w-5 h-5 rounded-full bg-amber-500/10 flex items-center justify-center shrink-0 mt-0.5">
                            <AlertTriangle className="w-3 h-3 text-amber-500" />
                          </div>
                          <span className="leading-tight">{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Red Flags */}
                {realityCheck.red_flags && realityCheck.red_flags.length > 0 && (
                  <div className="p-5 rounded-xl bg-red-500/5 border border-red-500/20">
                    <h4 className="font-bold mb-4 text-red-600/80 uppercase tracking-wider text-xs flex items-center gap-2">
                      <AlertTriangle className="w-4 h-4" />
                      Red Flags
                    </h4>
                    <ul className="space-y-3">
                      {realityCheck.red_flags.map((flag, i) => (
                        <li key={i} className="text-sm flex items-start gap-3 text-red-700/90 dark:text-red-400">
                          <span className="text-red-500 mt-0.5">•</span>
                          <span className="leading-tight">{flag}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Green Flags */}
                {realityCheck.green_flags && realityCheck.green_flags.length > 0 && (
                  <div className="p-5 rounded-xl bg-green-500/5 border border-green-500/20">
                    <h4 className="font-bold mb-4 text-green-600/80 uppercase tracking-wider text-xs flex items-center gap-2">
                      <CheckCircle className="w-4 h-4" />
                      Green Flags
                    </h4>
                    <ul className="space-y-3">
                      {realityCheck.green_flags.map((flag, i) => (
                        <li key={i} className="text-sm flex items-start gap-3 text-green-700/90 dark:text-green-400">
                          <span className="text-green-500 mt-0.5">•</span>
                          <span className="leading-tight">{flag}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </motion.div>
          )}

          {/* Communities Results */}
          {communities && (
            <motion.div 
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              className="mb-12 space-y-8"
            >
              <div className="pb-4 border-b">
                <h3 className="text-2xl font-display font-bold flex items-center gap-3">
                  <Users className="w-6 h-6 text-primary" />
                  Discovered Communities
                </h3>
              </div>

              {communities.reddit && communities.reddit.length > 0 && (
                <div className="p-6 rounded-2xl border bg-card shadow-sm">
                  <h4 className="font-bold text-lg mb-4 flex items-center gap-2 text-orange-500">
                    <ExternalLink className="w-5 h-5" />
                    Reddit Communities
                  </h4>
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    {communities.reddit.map((sub, i) => (
                      <div key={i} className="p-4 rounded-xl border bg-background hover:border-orange-500/30 transition-colors">
                        <div className="font-bold text-orange-600 dark:text-orange-400 text-lg mb-1">{sub.name}</div>
                        <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">{sub.subscribers} subscribers</div>
                        <div className="text-sm leading-relaxed text-foreground/80">{sub.relevance}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {communities.discord && communities.discord.length > 0 && (
                <div className="p-6 rounded-2xl border bg-card shadow-sm">
                  <h4 className="font-bold text-lg mb-4 flex items-center gap-2 text-indigo-500">
                    <MessageCircle className="w-5 h-5" />
                    Discord Servers
                  </h4>
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    {communities.discord.map((server, i) => (
                      <div key={i} className="p-4 rounded-xl border bg-background hover:border-indigo-500/30 transition-colors">
                        <div className="font-bold text-indigo-600 dark:text-indigo-400 text-lg mb-2">{server.name}</div>
                        <div className="text-sm leading-relaxed text-foreground/80 mb-3">{server.description}</div>
                        <div className="text-xs font-medium text-muted-foreground bg-muted p-2 rounded-md">{server.invite_hint}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {communities.twitter && communities.twitter.length > 0 && (
                <div className="p-6 rounded-2xl border bg-card shadow-sm">
                  <h4 className="font-bold text-lg mb-4 flex items-center gap-2 text-sky-500">
                    <Hash className="w-5 h-5" />
                    Twitter/X Targets
                  </h4>
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    {communities.twitter.map((tag, i) => (
                      <div key={i} className="p-4 rounded-xl border bg-background hover:border-sky-500/30 transition-colors">
                        <div className="font-bold text-sky-600 dark:text-sky-400 text-lg mb-2">{tag.hashtag}</div>
                        <div className="text-sm leading-relaxed text-foreground/80 mb-3">{tag.usage}</div>
                        <div className="text-xs font-medium text-muted-foreground bg-muted p-2 rounded-md">{tag.tip}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {communities.other && communities.other.length > 0 && (
                <div className="p-6 rounded-2xl border bg-card shadow-sm">
                  <h4 className="font-bold text-lg mb-4 flex items-center gap-2 text-green-500">
                    <Globe className="w-5 h-5" />
                    Other Platforms
                  </h4>
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    {communities.other.map((community, i) => (
                      <div key={i} className="p-4 rounded-xl border bg-background hover:border-green-500/30 transition-colors">
                        <div className="font-bold text-green-600 dark:text-green-400 text-lg mb-1">{community.platform}</div>
                        <div className="text-sm font-medium text-foreground mb-3">{community.community}</div>
                        <div className="text-sm leading-relaxed text-foreground/80">{community.description}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {communities.timing_tips && communities.timing_tips.length > 0 && (
                <div className="p-6 rounded-2xl bg-primary/5 border border-primary/20">
                  <h4 className="font-bold text-lg mb-4 text-primary">Strategic Sharing Tips</h4>
                  <ul className="grid gap-3 sm:grid-cols-2">
                    {communities.timing_tips.map((tip, i) => (
                      <li key={i} className="text-sm font-medium text-foreground/90 flex items-start gap-3 bg-background p-3 rounded-xl border border-primary/10">
                        <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                          <span className="text-primary font-bold text-xs">{i+1}</span>
                        </div>
                        <span className="mt-0.5">{tip}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </motion.div>
          )}
          </AnimatePresence>
        </motion.div>

        {/* PRD Document Section */}
        <motion.div variants={fadeIn} className="border-2 border-border/60 rounded-3xl overflow-hidden bg-card shadow-lg">
          <button
            onClick={() => setIsPrdExpanded(!isPrdExpanded)}
            className="w-full flex items-center justify-between p-6 bg-card hover:bg-muted/30 transition-colors group"
            data-testid="button-toggle-prd"
          >
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center border border-primary/20 group-hover:bg-primary group-hover:text-primary-foreground transition-colors text-primary">
                <FileText className="w-6 h-6" />
              </div>
              <div className="text-left">
                <h3 className="text-2xl font-display font-bold">Product Requirements Document</h3>
                <p className="text-sm font-medium text-muted-foreground mt-1">View, edit format, and export your complete specification</p>
              </div>
            </div>
            <div className={`w-10 h-10 rounded-full flex items-center justify-center transition-colors ${isPrdExpanded ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground group-hover:bg-primary/20 group-hover:text-primary'}`}>
              {isPrdExpanded ? (
                <ChevronUp className="w-6 h-6" />
              ) : (
                <ChevronDown className="w-6 h-6" />
              )}
            </div>
          </button>
          
          <AnimatePresence>
            {isPrdExpanded && (
              <motion.div 
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: "auto", opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="overflow-hidden"
              >
                <div className="p-6 md:p-8 border-t bg-background">
                  {/* Format Selection */}
                  <div className="flex flex-col sm:flex-row flex-wrap gap-3 mb-8 pb-6 border-b">
                    <div className="flex flex-wrap gap-2 w-full sm:w-auto">
                      {FORMAT_OPTIONS.map((format) => {
                        const Icon = format.icon;
                        const isActive = currentFormat === format.id;
                        return (
                          <button
                            key={format.id}
                            onClick={() => generatePRD(format.id)}
                            disabled={isGenerating}
                            className={`
                              flex items-center gap-2 px-5 py-2.5 rounded-xl border-2 font-bold transition-all
                              ${isActive 
                                ? "border-primary bg-primary/10 text-primary shadow-sm" 
                                : "border-border hover:border-primary/50 bg-card text-muted-foreground hover:text-foreground"}
                              ${isGenerating ? "opacity-50 cursor-not-allowed" : ""}
                            `}
                            data-testid={`format-${format.id}`}
                          >
                            {isGenerating && currentFormat === format.id ? (
                              <Loader2 className="w-4 h-4 animate-spin" />
                            ) : (
                              <Icon className="w-4 h-4" />
                            )}
                            <span>{format.label}</span>
                          </button>
                        );
                      })}
                    </div>
                    <Button
                      variant="outline"
                      onClick={() => generatePRD(currentFormat)}
                      disabled={isGenerating}
                      className="sm:ml-auto h-11 px-5 rounded-xl font-bold border-2 hover:bg-muted"
                      data-testid="button-regenerate"
                    >
                      <RefreshCw className={`w-4 h-4 mr-2 ${isGenerating ? "animate-spin" : ""}`} />
                      Regenerate View
                    </Button>
                  </div>

                  {/* View Mode Toggle */}
                  <div className="flex bg-muted/50 p-1.5 rounded-xl mb-8 w-fit border">
                    <button
                      onClick={() => setViewMode("formatted")}
                      className={`px-6 py-2 text-sm font-bold rounded-lg transition-all ${
                        viewMode === "formatted" 
                          ? "bg-background text-foreground shadow-sm" 
                          : "text-muted-foreground hover:text-foreground hover:bg-muted"
                      }`}
                      data-testid="button-view-formatted"
                    >
                      Formatted Document
                    </button>
                    <button
                      onClick={() => setViewMode("raw")}
                      className={`px-6 py-2 text-sm font-bold rounded-lg transition-all ${
                        viewMode === "raw" 
                          ? "bg-background text-foreground shadow-sm" 
                          : "text-muted-foreground hover:text-foreground hover:bg-muted"
                      }`}
                      data-testid="button-view-raw"
                    >
                      Raw Markdown
                    </button>
                  </div>

                  {/* PRD Content */}
                  <div className="bg-card rounded-2xl border shadow-inner p-6 md:p-10 min-h-[500px]">
                    {viewMode === "formatted" ? (
                      <div className="prose prose-slate dark:prose-invert max-w-none break-words overflow-wrap-anywhere prose-headings:font-display prose-h1:text-4xl prose-h1:font-black prose-h2:text-3xl prose-h2:font-bold prose-h2:mt-12 prose-h2:border-b prose-h2:pb-4 prose-h3:text-2xl prose-h3:mt-8 prose-p:text-foreground/90 prose-p:leading-relaxed prose-a:text-primary hover:prose-a:text-primary/80 prose-strong:text-foreground prose-strong:font-bold prose-ul:my-6 prose-li:my-2 marker:text-primary">
                        <ReactMarkdown
                          components={{
                            code: ({ className, children, ...props }: any) => {
                              const match = /language-(\w+)/.exec(className || '');
                              return match ? (
                                <div className="relative rounded-xl overflow-hidden my-6 border shadow-sm">
                                  <div className="bg-muted px-4 py-2 text-xs font-bold text-muted-foreground border-b border-border uppercase tracking-wider">{match[1]}</div>
                                  <pre className="!m-0 !rounded-none !bg-card p-4 overflow-x-auto text-sm leading-relaxed" {...props}>
                                    <code className="text-foreground">{children}</code>
                                  </pre>
                                </div>
                              ) : (
                                <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono border font-medium text-primary" {...props}>
                                  {children}
                                </code>
                              );
                            },
                          }}
                        >
                          {project.prdContent?.replace(/^```(?:markdown)?\n?/i, "").replace(/\n?```$/i, "").trim()}
                        </ReactMarkdown>
                      </div>
                    ) : (
                      <div className="h-full" data-testid="raw-markdown-view">
                        <pre className="text-sm font-mono whitespace-pre-wrap break-words text-foreground/90 leading-relaxed font-medium">
                          {project.prdContent}
                        </pre>
                      </div>
                    )}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </div>
    </AppLayout>
  );
}